apiVersion: apps/v1
kind: Deployment
metadata:
  name: expire-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expire
  template:
    metadata:
      labels:
        app: expire
    spec:
      containers:
        - name: expire
          image: penkong/stubhub-expire
          env:
            - name: NATS_URL
              value: 'http://nats-service:4222'
            - name: NATS_CLUSTER_ID
              value: 'ticketing'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_HOST
              value: expire-redis-service
